eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8671/eureka
      
server:
  port: 8082
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: user-service
        uri:
          lb://USER-SERVICE
        predicates:
        - Path=/user/**
      
      - id: budget-expense
        uri:
          lb://BUDGET-SERVICE
        predicates:
        - Path=/budget/**
        - Path=/expenses/**
        - Path=/category/** 
        filters:
        - AuthenticationFilter
        
      - id: financial-goal
        uri:
          lb://FINANCIAL-GOAL
        predicates:
        - Path=/goal/**
        filters:
        - AuthenticationFilter
        
      